// src-tauri/src/obsidian.rs
// Project VERA — Obsidian Vault Bridge
// Native filesystem write/read operations for Obsidian .md vault integration.

use crate::models::ObsidianWriteRequest;
use anyhow::{Context, Result};
use chrono::Utc;
use std::path::{Path, PathBuf};

pub struct ObsidianBridge {
    vault_path: PathBuf,
}

impl ObsidianBridge {
    /// Initializes the Obsidian bridge.
    /// Resolves vault path in this priority order:
    /// 1. Explicitly configured path from models.json
    /// 2. VERA's own auto-managed vault in the user's documents
    /// 3. Current directory fallback for portable installs
    pub fn new(vault_path: Option<PathBuf>) -> Self {
        let resolved = vault_path.unwrap_or_else(|| Self::default_vault_path());
        Self {
            vault_path: resolved,
        }
    }

    /// Returns the default vault path (Documents/VERA-Vault).
    fn default_vault_path() -> PathBuf {
        PathBuf::from(r"E:\Second Brain")
    }

    /// Writes content to a markdown file in the configured vault.
    /// Creates the vault directory and any sub-paths if they don't exist.
    pub async fn write_note(&self, request: ObsidianWriteRequest) -> Result<PathBuf> {
        // Sanitize the filename — only allow safe characters
        let safe_filename = Self::sanitize_filename(&request.filename);
        let vault_base = request
            .vault_path
            .as_deref()
            .map(PathBuf::from)
            .unwrap_or_else(|| self.vault_path.clone());

        // Ensure vault directory exists
        tokio::fs::create_dir_all(&vault_base)
            .await
            .with_context(|| format!("Failed to create vault directory: {}", vault_base.display()))?;

        let file_path = vault_base.join(&safe_filename);

        // Build final content with frontmatter if provided
        let final_content = if let Some(fm) = &request.frontmatter {
            let frontmatter_str = Self::build_frontmatter(fm);
            format!("{}\n{}", frontmatter_str, request.content)
        } else {
            Self::prepend_vera_header(&request.content, &request.filename)
        };

        if request.append && file_path.exists() {
            // Append mode: add a separator and new content
            let existing = tokio::fs::read_to_string(&file_path)
                .await
                .unwrap_or_default();
            let separator = format!(
                "\n\n---\n*Appended by VERA — {}*\n\n",
                Utc::now().format("%Y-%m-%d %H:%M:%S UTC")
            );
            let new_content = format!("{}{}{}", existing, separator, request.content);
            tokio::fs::write(&file_path, new_content)
                .await
                .with_context(|| format!("Failed to append to: {}", file_path.display()))?;
        } else {
            // Write mode: create or overwrite
            tokio::fs::write(&file_path, final_content)
                .await
                .with_context(|| format!("Failed to write file: {}", file_path.display()))?;
        }

        log::info!("VERA Obsidian Bridge: wrote '{}'", file_path.display());
        Ok(file_path)
    }

    /// Reads a note from the vault.
    pub async fn read_note(&self, filename: &str) -> Result<String> {
        let safe = Self::sanitize_filename(filename);
        let path = self.vault_path.join(&safe);
        tokio::fs::read_to_string(&path)
            .await
            .with_context(|| format!("Cannot read vault note: {}", path.display()))
    }

    /// Lists all .md files in the vault, recursively.
    pub async fn list_notes(&self) -> Result<Vec<String>> {
        let mut notes = Vec::new();
        Self::walk_dir(&self.vault_path, &mut notes).await?;
        Ok(notes)
    }

    /// Appends to the VERA session log (a special running log file in the vault).
    pub async fn append_session_log(&self, entry: &str) -> Result<()> {
        let log_path = self.vault_path.join("VERA-Session-Log.md");
        let timestamp = Utc::now().format("%Y-%m-%d %H:%M:%S UTC");
        let log_entry = format!("\n### {} \n{}\n", timestamp, entry);

        if !log_path.exists() {
            let header = format!(
                "# VERA Session Log\n*Auto-generated by Project VERA*\n\n---\n{}\n",
                log_entry
            );
            tokio::fs::create_dir_all(&self.vault_path).await?;
            tokio::fs::write(&log_path, header).await?;
        } else {
            use tokio::io::AsyncWriteExt;
            let mut file = tokio::fs::OpenOptions::new()
                .append(true)
                .open(&log_path)
                .await?;
            file.write_all(log_entry.as_bytes()).await?;
        }
        Ok(())
    }

    /// Checks if an Obsidian vault exists at the given path
    /// (looks for .obsidian directory which Obsidian creates automatically).
    pub fn is_obsidian_vault(path: &Path) -> bool {
        path.join(".obsidian").is_dir()
    }

    /// Returns the current vault path.
    pub fn vault_path(&self) -> &Path {
        &self.vault_path
    }

    // ── Private Helpers ───────────────────────────────────────────────────────

    fn sanitize_filename(name: &str) -> String {
        // Strip path separators and dangerous chars, keep .md extension
        let safe: String = name
            .chars()
            .map(|c| match c {
                '/' | '\\' | ':' | '*' | '?' | '"' | '<' | '>' | '|' => '-',
                c => c,
            })
            .collect();

        // Ensure .md extension
        if safe.ends_with(".md") {
            safe
        } else {
            format!("{}.md", safe)
        }
    }

    fn prepend_vera_header(content: &str, title: &str) -> String {
        let ts = Utc::now().format("%Y-%m-%d");
        format!(
            "---\ntitle: {}\ncreated: {}\nsource: VERA Orchestrator\ntags: [vera, auto-generated]\n---\n\n{}",
            title, ts, content
        )
    }

    fn build_frontmatter(fm: &std::collections::HashMap<String, serde_json::Value>) -> String {
        let mut lines = vec!["---".to_string()];
        for (key, val) in fm {
            lines.push(format!("{}: {}", key, val));
        }
        lines.push("---".to_string());
        lines.join("\n")
    }

    async fn walk_dir(dir: &Path, results: &mut Vec<String>) -> Result<()> {
        if !dir.is_dir() {
            return Ok(());
        }
        let mut entries = tokio::fs::read_dir(dir).await?;
        while let Some(entry) = entries.next_entry().await? {
            let path = entry.path();
            if path.is_dir() {
                Box::pin(Self::walk_dir(&path, results)).await?;
            } else if path.extension().and_then(|s| s.to_str()) == Some("md") {
                if let Some(s) = path.to_str() {
                    results.push(s.to_string());
                }
            }
        }
        Ok(())
    }
}
